name: Cache Dependencies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prime the cache
      - name: Prime cache-a2fe9dd
        id: prime-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm  # change this depending on your package manager
          key: cache-a2fe9dd
          restore-keys: |
            cache-a2fe9dd

      # Echo cache hit/miss
      - name: Cache result
        run: echo "Cache hit: ${{ steps.prime-cache.outputs.cache-hit }}"
      
      # Example: install dependencies
      - name: Install dependencies
        run: npm install
