name: Daily Auto Commit

on:
  schedule:
    - cron: '30 14 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with 24f2000880@ds.study.iitm.ac.in
      uses: actions/checkout@v4

    - name: Setup Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "24f2000880@ds.study.iitm.ac.in"

    - name: Make daily commit
      run: |
        date > daily.txt
        git add daily.txt
        git commit -m "Daily commit" || true
        git push
